#!/bin/bash

baseDir="/home/yuanjial/Projects/Python-pure/instanceinference/code/Cython/cython_merge/include/"

#g++ -std=c++14 testDataTempl.cxx -o aTest -g -I $baseDir

g++ -std=c++14 testMerge.cxx -o aTestMerge -g -I $baseDir

#g++ -std=c++14 testGraph.cxx -o graphTest -g -I $baseDir
