#!/bin/bash

baseDir="/home/yuanjial/Projects/Python-pure/instanceinference/code/Cython/cython_segments/include/"

#g++ -std=c++14 testDataTempl.cxx -o aTest -g -I $baseDir

#g++ -std=c++14 testSegmentFitting.cxx -o aTest -g -I $baseDir

g++ -std=c++14 ../include/svm/svm.cpp testSegmentGrow.cxx -o aTestGrow -g -I $baseDir

#g++ -std=c++14 testSegmentGrow.cxx -o aTestGrow -I $baseDir 

#g++ -std=c++14 testGraph.cxx -o graphTest -g -I $baseDir
