#!/bin/bash

mv SegmentFitting.hxx SegmentFitting_reg.hxx
mv SegmentFitting_cls.hxx SegmentFitting.hxx

mv SegmentGrow.hxx SegmentGrow_reg.hxx
mv SegmentGrow_cls.hxx SegmentGrow.hxx

mv utils/PlatformDefs.hxx utils/PlatformDefs_reg.hxx
mv utils/PlatformDefs_cls.hxx utils/PlatformDefs.hxx
