#!/bin/bash

#g++ -std=c++1y testDataTempl.cxx -o aTest -g -I "/home/yuanjial/Code/Python-pure/instanceinference-dir/code/Cython/cython_segments/include/"

#g++ -std=c++1y testSegmentFitting.cxx -o aTest -g -I "/home/yuanjial/Code/Python-pure/instanceinference-dir/code/Cython/cython_segments/include/"

g++ -std=c++1y testSegmentGrow.cxx -o aTestGrow -g -I "/home/yuanjial/Code/Python-pure/instanceinference-dir/code/Cython/cython_segments/include/"

#g++ -std=c++1y testGraph.cxx -o graphTest -g -I "/home/yuanjial/Code/Python-pure/instanceinference-dir/code/Cython/cython_segments/include/"
